// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: client.proto

package admin

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on ListClientRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ListClientRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListClientRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListClientRequestMultiError, or nil if none found.
func (m *ListClientRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListClientRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for PageSize

	// no validation rules for Page

	if len(errors) > 0 {
		return ListClientRequestMultiError(errors)
	}

	return nil
}

// ListClientRequestMultiError is an error wrapping multiple validation errors
// returned by ListClientRequest.ValidateAll() if the designated constraints
// aren't met.
type ListClientRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListClientRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListClientRequestMultiError) AllErrors() []error { return m }

// ListClientRequestValidationError is the validation error returned by
// ListClientRequest.Validate if the designated constraints aren't met.
type ListClientRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListClientRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListClientRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListClientRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListClientRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListClientRequestValidationError) ErrorName() string {
	return "ListClientRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListClientRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListClientRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListClientRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListClientRequestValidationError{}

// Validate checks the field values on ListClientResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListClientResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListClientResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListClientResponseMultiError, or nil if none found.
func (m *ListClientResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListClientResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetClients() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListClientResponseValidationError{
						field:  fmt.Sprintf("Clients[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListClientResponseValidationError{
						field:  fmt.Sprintf("Clients[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListClientResponseValidationError{
					field:  fmt.Sprintf("Clients[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for TotalCount

	if len(errors) > 0 {
		return ListClientResponseMultiError(errors)
	}

	return nil
}

// ListClientResponseMultiError is an error wrapping multiple validation errors
// returned by ListClientResponse.ValidateAll() if the designated constraints
// aren't met.
type ListClientResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListClientResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListClientResponseMultiError) AllErrors() []error { return m }

// ListClientResponseValidationError is the validation error returned by
// ListClientResponse.Validate if the designated constraints aren't met.
type ListClientResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListClientResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListClientResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListClientResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListClientResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListClientResponseValidationError) ErrorName() string {
	return "ListClientResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListClientResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListClientResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListClientResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListClientResponseValidationError{}

// Validate checks the field values on GetClientRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetClientRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetClientRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetClientRequestMultiError, or nil if none found.
func (m *GetClientRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetClientRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ClientId

	if len(errors) > 0 {
		return GetClientRequestMultiError(errors)
	}

	return nil
}

// GetClientRequestMultiError is an error wrapping multiple validation errors
// returned by GetClientRequest.ValidateAll() if the designated constraints
// aren't met.
type GetClientRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetClientRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetClientRequestMultiError) AllErrors() []error { return m }

// GetClientRequestValidationError is the validation error returned by
// GetClientRequest.Validate if the designated constraints aren't met.
type GetClientRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetClientRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetClientRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetClientRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetClientRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetClientRequestValidationError) ErrorName() string { return "GetClientRequestValidationError" }

// Error satisfies the builtin error interface
func (e GetClientRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetClientRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetClientRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetClientRequestValidationError{}

// Validate checks the field values on GetClientResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetClientResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetClientResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetClientResponseMultiError, or nil if none found.
func (m *GetClientResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetClientResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetClient()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetClientResponseValidationError{
					field:  "Client",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetClientResponseValidationError{
					field:  "Client",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetClient()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetClientResponseValidationError{
				field:  "Client",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetClientResponseMultiError(errors)
	}

	return nil
}

// GetClientResponseMultiError is an error wrapping multiple validation errors
// returned by GetClientResponse.ValidateAll() if the designated constraints
// aren't met.
type GetClientResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetClientResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetClientResponseMultiError) AllErrors() []error { return m }

// GetClientResponseValidationError is the validation error returned by
// GetClientResponse.Validate if the designated constraints aren't met.
type GetClientResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetClientResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetClientResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetClientResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetClientResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetClientResponseValidationError) ErrorName() string {
	return "GetClientResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetClientResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetClientResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetClientResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetClientResponseValidationError{}

// Validate checks the field values on DeleteClientRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteClientRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteClientRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteClientRequestMultiError, or nil if none found.
func (m *DeleteClientRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteClientRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ClientId

	// no validation rules for CleanSession

	if len(errors) > 0 {
		return DeleteClientRequestMultiError(errors)
	}

	return nil
}

// DeleteClientRequestMultiError is an error wrapping multiple validation
// errors returned by DeleteClientRequest.ValidateAll() if the designated
// constraints aren't met.
type DeleteClientRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteClientRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteClientRequestMultiError) AllErrors() []error { return m }

// DeleteClientRequestValidationError is the validation error returned by
// DeleteClientRequest.Validate if the designated constraints aren't met.
type DeleteClientRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteClientRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteClientRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteClientRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteClientRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteClientRequestValidationError) ErrorName() string {
	return "DeleteClientRequestValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteClientRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteClientRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteClientRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteClientRequestValidationError{}

// Validate checks the field values on Client with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Client) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Client with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in ClientMultiError, or nil if none found.
func (m *Client) ValidateAll() error {
	return m.validate(true)
}

func (m *Client) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ClientId

	// no validation rules for Username

	// no validation rules for KeepAlive

	// no validation rules for Version

	// no validation rules for RemoteAddr

	// no validation rules for LocalAddr

	if all {
		switch v := interface{}(m.GetConnectedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ClientValidationError{
					field:  "ConnectedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ClientValidationError{
					field:  "ConnectedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetConnectedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ClientValidationError{
				field:  "ConnectedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetDisconnectedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ClientValidationError{
					field:  "DisconnectedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ClientValidationError{
					field:  "DisconnectedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetDisconnectedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ClientValidationError{
				field:  "DisconnectedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for SessionExpiry

	// no validation rules for MaxInflight

	// no validation rules for InflightLen

	// no validation rules for MaxQueue

	// no validation rules for QueueLen

	// no validation rules for SubscriptionsCurrent

	// no validation rules for SubscriptionsTotal

	// no validation rules for PacketsReceivedBytes

	// no validation rules for PacketsReceivedNums

	// no validation rules for PacketsSendBytes

	// no validation rules for PacketsSendNums

	// no validation rules for MessageDropped

	if len(errors) > 0 {
		return ClientMultiError(errors)
	}

	return nil
}

// ClientMultiError is an error wrapping multiple validation errors returned by
// Client.ValidateAll() if the designated constraints aren't met.
type ClientMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ClientMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ClientMultiError) AllErrors() []error { return m }

// ClientValidationError is the validation error returned by Client.Validate if
// the designated constraints aren't met.
type ClientValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ClientValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ClientValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ClientValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ClientValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ClientValidationError) ErrorName() string { return "ClientValidationError" }

// Error satisfies the builtin error interface
func (e ClientValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sClient.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ClientValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ClientValidationError{}
