// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: publish.proto

package admin

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PublishRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	TopicName string                 `protobuf:"bytes,1,opt,name=topic_name,json=topicName,proto3" json:"topic_name,omitempty"`
	Payload   string                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Qos       uint32                 `protobuf:"varint,3,opt,name=qos,proto3" json:"qos,omitempty"`
	Retained  bool                   `protobuf:"varint,4,opt,name=retained,proto3" json:"retained,omitempty"`
	// the following fields are using in v5 client.
	ContentType     string            `protobuf:"bytes,5,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	CorrelationData string            `protobuf:"bytes,6,opt,name=correlation_data,json=correlationData,proto3" json:"correlation_data,omitempty"`
	MessageExpiry   uint32            `protobuf:"varint,7,opt,name=message_expiry,json=messageExpiry,proto3" json:"message_expiry,omitempty"`
	PayloadFormat   uint32            `protobuf:"varint,8,opt,name=payload_format,json=payloadFormat,proto3" json:"payload_format,omitempty"`
	ResponseTopic   string            `protobuf:"bytes,9,opt,name=response_topic,json=responseTopic,proto3" json:"response_topic,omitempty"`
	UserProperties  []*UserProperties `protobuf:"bytes,10,rep,name=user_properties,json=userProperties,proto3" json:"user_properties,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PublishRequest) Reset() {
	*x = PublishRequest{}
	mi := &file_publish_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishRequest) ProtoMessage() {}

func (x *PublishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_publish_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishRequest.ProtoReflect.Descriptor instead.
func (*PublishRequest) Descriptor() ([]byte, []int) {
	return file_publish_proto_rawDescGZIP(), []int{0}
}

func (x *PublishRequest) GetTopicName() string {
	if x != nil {
		return x.TopicName
	}
	return ""
}

func (x *PublishRequest) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *PublishRequest) GetQos() uint32 {
	if x != nil {
		return x.Qos
	}
	return 0
}

func (x *PublishRequest) GetRetained() bool {
	if x != nil {
		return x.Retained
	}
	return false
}

func (x *PublishRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *PublishRequest) GetCorrelationData() string {
	if x != nil {
		return x.CorrelationData
	}
	return ""
}

func (x *PublishRequest) GetMessageExpiry() uint32 {
	if x != nil {
		return x.MessageExpiry
	}
	return 0
}

func (x *PublishRequest) GetPayloadFormat() uint32 {
	if x != nil {
		return x.PayloadFormat
	}
	return 0
}

func (x *PublishRequest) GetResponseTopic() string {
	if x != nil {
		return x.ResponseTopic
	}
	return ""
}

func (x *PublishRequest) GetUserProperties() []*UserProperties {
	if x != nil {
		return x.UserProperties
	}
	return nil
}

type UserProperties struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	K             []byte                 `protobuf:"bytes,1,opt,name=K,proto3" json:"K,omitempty"`
	V             []byte                 `protobuf:"bytes,2,opt,name=V,proto3" json:"V,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserProperties) Reset() {
	*x = UserProperties{}
	mi := &file_publish_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProperties) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProperties) ProtoMessage() {}

func (x *UserProperties) ProtoReflect() protoreflect.Message {
	mi := &file_publish_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProperties.ProtoReflect.Descriptor instead.
func (*UserProperties) Descriptor() ([]byte, []int) {
	return file_publish_proto_rawDescGZIP(), []int{1}
}

func (x *UserProperties) GetK() []byte {
	if x != nil {
		return x.K
	}
	return nil
}

func (x *UserProperties) GetV() []byte {
	if x != nil {
		return x.V
	}
	return nil
}

var File_publish_proto protoreflect.FileDescriptor

const file_publish_proto_rawDesc = "" +
	"\n" +
	"\rpublish.proto\x12\x0fgmqtt.admin.api\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x84\x03\n" +
	"\x0ePublishRequest\x12\x1d\n" +
	"\n" +
	"topic_name\x18\x01 \x01(\tR\ttopicName\x12\x18\n" +
	"\apayload\x18\x02 \x01(\tR\apayload\x12\x10\n" +
	"\x03qos\x18\x03 \x01(\rR\x03qos\x12\x1a\n" +
	"\bretained\x18\x04 \x01(\bR\bretained\x12!\n" +
	"\fcontent_type\x18\x05 \x01(\tR\vcontentType\x12)\n" +
	"\x10correlation_data\x18\x06 \x01(\tR\x0fcorrelationData\x12%\n" +
	"\x0emessage_expiry\x18\a \x01(\rR\rmessageExpiry\x12%\n" +
	"\x0epayload_format\x18\b \x01(\rR\rpayloadFormat\x12%\n" +
	"\x0eresponse_topic\x18\t \x01(\tR\rresponseTopic\x12H\n" +
	"\x0fuser_properties\x18\n" +
	" \x03(\v2\x1f.gmqtt.admin.api.UserPropertiesR\x0euserProperties\",\n" +
	"\x0eUserProperties\x12\f\n" +
	"\x01K\x18\x01 \x01(\fR\x01K\x12\f\n" +
	"\x01V\x18\x02 \x01(\fR\x01V2l\n" +
	"\x0ePublishService\x12Z\n" +
	"\aPublish\x12\x1f.gmqtt.admin.api.PublishRequest\x1a\x16.google.protobuf.Empty\"\x16\x82\xd3\xe4\x93\x02\x10:\x01*\"\v/v1/publishB\xa2\x01\n" +
	"\x13com.gmqtt.admin.apiB\fPublishProtoP\x01Z\x1fgithub.com/DrmagicE/gmqtt/admin\xa2\x02\x03GAA\xaa\x02\x0fGmqtt.Admin.Api\xca\x02\x0fGmqtt\\Admin\\Api\xe2\x02\x1bGmqtt\\Admin\\Api\\GPBMetadata\xea\x02\x11Gmqtt::Admin::Apib\x06proto3"

var (
	file_publish_proto_rawDescOnce sync.Once
	file_publish_proto_rawDescData []byte
)

func file_publish_proto_rawDescGZIP() []byte {
	file_publish_proto_rawDescOnce.Do(func() {
		file_publish_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_publish_proto_rawDesc), len(file_publish_proto_rawDesc)))
	})
	return file_publish_proto_rawDescData
}

var file_publish_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_publish_proto_goTypes = []any{
	(*PublishRequest)(nil), // 0: gmqtt.admin.api.PublishRequest
	(*UserProperties)(nil), // 1: gmqtt.admin.api.UserProperties
	(*emptypb.Empty)(nil),  // 2: google.protobuf.Empty
}
var file_publish_proto_depIdxs = []int32{
	1, // 0: gmqtt.admin.api.PublishRequest.user_properties:type_name -> gmqtt.admin.api.UserProperties
	0, // 1: gmqtt.admin.api.PublishService.Publish:input_type -> gmqtt.admin.api.PublishRequest
	2, // 2: gmqtt.admin.api.PublishService.Publish:output_type -> google.protobuf.Empty
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_publish_proto_init() }
func file_publish_proto_init() {
	if File_publish_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_publish_proto_rawDesc), len(file_publish_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_publish_proto_goTypes,
		DependencyIndexes: file_publish_proto_depIdxs,
		MessageInfos:      file_publish_proto_msgTypes,
	}.Build()
	File_publish_proto = out.File
	file_publish_proto_goTypes = nil
	file_publish_proto_depIdxs = nil
}
