// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: subscription.proto

package admin

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubFilterType int32

const (
	SubFilterType_SUB_FILTER_TYPE_SYS_UNSPECIFIED SubFilterType = 0
	SubFilterType_SUB_FILTER_TYPE_SYS             SubFilterType = 1
	SubFilterType_SUB_FILTER_TYPE_SHARED          SubFilterType = 2
	SubFilterType_SUB_FILTER_TYPE_NON_SHARED      SubFilterType = 3
)

// Enum value maps for SubFilterType.
var (
	SubFilterType_name = map[int32]string{
		0: "SUB_FILTER_TYPE_SYS_UNSPECIFIED",
		1: "SUB_FILTER_TYPE_SYS",
		2: "SUB_FILTER_TYPE_SHARED",
		3: "SUB_FILTER_TYPE_NON_SHARED",
	}
	SubFilterType_value = map[string]int32{
		"SUB_FILTER_TYPE_SYS_UNSPECIFIED": 0,
		"SUB_FILTER_TYPE_SYS":             1,
		"SUB_FILTER_TYPE_SHARED":          2,
		"SUB_FILTER_TYPE_NON_SHARED":      3,
	}
)

func (x SubFilterType) Enum() *SubFilterType {
	p := new(SubFilterType)
	*p = x
	return p
}

func (x SubFilterType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SubFilterType) Descriptor() protoreflect.EnumDescriptor {
	return file_subscription_proto_enumTypes[0].Descriptor()
}

func (SubFilterType) Type() protoreflect.EnumType {
	return &file_subscription_proto_enumTypes[0]
}

func (x SubFilterType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SubFilterType.Descriptor instead.
func (SubFilterType) EnumDescriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{0}
}

type SubMatchType int32

const (
	SubMatchType_SUB_MATCH_TYPE_MATCH_UNSPECIFIED SubMatchType = 0
	SubMatchType_SUB_MATCH_TYPE_MATCH_NAME        SubMatchType = 1
	SubMatchType_SUB_MATCH_TYPE_MATCH_FILTER      SubMatchType = 2
)

// Enum value maps for SubMatchType.
var (
	SubMatchType_name = map[int32]string{
		0: "SUB_MATCH_TYPE_MATCH_UNSPECIFIED",
		1: "SUB_MATCH_TYPE_MATCH_NAME",
		2: "SUB_MATCH_TYPE_MATCH_FILTER",
	}
	SubMatchType_value = map[string]int32{
		"SUB_MATCH_TYPE_MATCH_UNSPECIFIED": 0,
		"SUB_MATCH_TYPE_MATCH_NAME":        1,
		"SUB_MATCH_TYPE_MATCH_FILTER":      2,
	}
)

func (x SubMatchType) Enum() *SubMatchType {
	p := new(SubMatchType)
	*p = x
	return p
}

func (x SubMatchType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SubMatchType) Descriptor() protoreflect.EnumDescriptor {
	return file_subscription_proto_enumTypes[1].Descriptor()
}

func (SubMatchType) Type() protoreflect.EnumType {
	return &file_subscription_proto_enumTypes[1]
}

func (x SubMatchType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SubMatchType.Descriptor instead.
func (SubMatchType) EnumDescriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{1}
}

type ListSubscriptionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      uint32                 `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Page          uint32                 `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSubscriptionRequest) Reset() {
	*x = ListSubscriptionRequest{}
	mi := &file_subscription_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSubscriptionRequest) ProtoMessage() {}

func (x *ListSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*ListSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{0}
}

func (x *ListSubscriptionRequest) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListSubscriptionRequest) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

type ListSubscriptionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subscriptions []*Subscription        `protobuf:"bytes,1,rep,name=subscriptions,proto3" json:"subscriptions,omitempty"`
	TotalCount    uint32                 `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSubscriptionResponse) Reset() {
	*x = ListSubscriptionResponse{}
	mi := &file_subscription_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSubscriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSubscriptionResponse) ProtoMessage() {}

func (x *ListSubscriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSubscriptionResponse.ProtoReflect.Descriptor instead.
func (*ListSubscriptionResponse) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{1}
}

func (x *ListSubscriptionResponse) GetSubscriptions() []*Subscription {
	if x != nil {
		return x.Subscriptions
	}
	return nil
}

func (x *ListSubscriptionResponse) GetTotalCount() uint32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type FilterSubscriptionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// If set, only filter the subscriptions that belongs to the client.
	ClientId string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// filter_type indicates what kinds of topics are going to filter.
	// If there are multiple types, use ',' to separate. e.g : 1,2
	// There are 3 kinds of topic can be filtered, defined by SubFilterType:
	// 1 = System Topic(begin with '$')
	// 2 = Shared Topic
	// 3 = NonShared Topic
	FilterType string `protobuf:"bytes,2,opt,name=filter_type,json=filterType,proto3" json:"filter_type,omitempty"`
	// If 1 (SUB_MATCH_TYPE_MATCH_NAME), the server will return subscriptions which has the same topic name with request topic_name.
	// If 2 (SUB_MATCH_TYPE_MATCH_FILTER),the server will return subscriptions which match the request topic_name .
	// match_type must be set when filter_type is not empty.
	MatchType SubMatchType `protobuf:"varint,3,opt,name=match_type,json=matchType,proto3,enum=gmqtt.admin.api.SubMatchType" json:"match_type,omitempty"`
	// topic_name must be set when match_type is not zero.
	TopicName string `protobuf:"bytes,4,opt,name=topic_name,json=topicName,proto3" json:"topic_name,omitempty"`
	// The maximum subscriptions can be returned.
	Limit         int32 `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilterSubscriptionRequest) Reset() {
	*x = FilterSubscriptionRequest{}
	mi := &file_subscription_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilterSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterSubscriptionRequest) ProtoMessage() {}

func (x *FilterSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*FilterSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{2}
}

func (x *FilterSubscriptionRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *FilterSubscriptionRequest) GetFilterType() string {
	if x != nil {
		return x.FilterType
	}
	return ""
}

func (x *FilterSubscriptionRequest) GetMatchType() SubMatchType {
	if x != nil {
		return x.MatchType
	}
	return SubMatchType_SUB_MATCH_TYPE_MATCH_UNSPECIFIED
}

func (x *FilterSubscriptionRequest) GetTopicName() string {
	if x != nil {
		return x.TopicName
	}
	return ""
}

func (x *FilterSubscriptionRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type FilterSubscriptionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subscriptions []*Subscription        `protobuf:"bytes,1,rep,name=subscriptions,proto3" json:"subscriptions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilterSubscriptionResponse) Reset() {
	*x = FilterSubscriptionResponse{}
	mi := &file_subscription_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilterSubscriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterSubscriptionResponse) ProtoMessage() {}

func (x *FilterSubscriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterSubscriptionResponse.ProtoReflect.Descriptor instead.
func (*FilterSubscriptionResponse) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{3}
}

func (x *FilterSubscriptionResponse) GetSubscriptions() []*Subscription {
	if x != nil {
		return x.Subscriptions
	}
	return nil
}

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Subscriptions []*Subscription        `protobuf:"bytes,2,rep,name=subscriptions,proto3" json:"subscriptions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_subscription_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{4}
}

func (x *SubscribeRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *SubscribeRequest) GetSubscriptions() []*Subscription {
	if x != nil {
		return x.Subscriptions
	}
	return nil
}

type SubscribeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// indicates whether it is a new subscription or the subscription is already existed.
	New           []bool `protobuf:"varint,1,rep,packed,name=new,proto3" json:"new,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeResponse) Reset() {
	*x = SubscribeResponse{}
	mi := &file_subscription_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeResponse) ProtoMessage() {}

func (x *SubscribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeResponse.ProtoReflect.Descriptor instead.
func (*SubscribeResponse) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{5}
}

func (x *SubscribeResponse) GetNew() []bool {
	if x != nil {
		return x.New
	}
	return nil
}

type UnsubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Topics        []string               `protobuf:"bytes,2,rep,name=topics,proto3" json:"topics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnsubscribeRequest) Reset() {
	*x = UnsubscribeRequest{}
	mi := &file_subscription_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnsubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsubscribeRequest) ProtoMessage() {}

func (x *UnsubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsubscribeRequest.ProtoReflect.Descriptor instead.
func (*UnsubscribeRequest) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{6}
}

func (x *UnsubscribeRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *UnsubscribeRequest) GetTopics() []string {
	if x != nil {
		return x.Topics
	}
	return nil
}

type Subscription struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TopicName         string                 `protobuf:"bytes,1,opt,name=topic_name,json=topicName,proto3" json:"topic_name,omitempty"`
	Id                uint32                 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Qos               uint32                 `protobuf:"varint,3,opt,name=qos,proto3" json:"qos,omitempty"`
	NoLocal           bool                   `protobuf:"varint,4,opt,name=no_local,json=noLocal,proto3" json:"no_local,omitempty"`
	RetainAsPublished bool                   `protobuf:"varint,5,opt,name=retain_as_published,json=retainAsPublished,proto3" json:"retain_as_published,omitempty"`
	RetainHandling    uint32                 `protobuf:"varint,6,opt,name=retain_handling,json=retainHandling,proto3" json:"retain_handling,omitempty"`
	ClientId          string                 `protobuf:"bytes,7,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Subscription) Reset() {
	*x = Subscription{}
	mi := &file_subscription_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subscription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subscription) ProtoMessage() {}

func (x *Subscription) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subscription.ProtoReflect.Descriptor instead.
func (*Subscription) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{7}
}

func (x *Subscription) GetTopicName() string {
	if x != nil {
		return x.TopicName
	}
	return ""
}

func (x *Subscription) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Subscription) GetQos() uint32 {
	if x != nil {
		return x.Qos
	}
	return 0
}

func (x *Subscription) GetNoLocal() bool {
	if x != nil {
		return x.NoLocal
	}
	return false
}

func (x *Subscription) GetRetainAsPublished() bool {
	if x != nil {
		return x.RetainAsPublished
	}
	return false
}

func (x *Subscription) GetRetainHandling() uint32 {
	if x != nil {
		return x.RetainHandling
	}
	return 0
}

func (x *Subscription) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

var File_subscription_proto protoreflect.FileDescriptor

const file_subscription_proto_rawDesc = "" +
	"\n" +
	"\x12subscription.proto\x12\x0fgmqtt.admin.api\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\"J\n" +
	"\x17ListSubscriptionRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\rR\bpageSize\x12\x12\n" +
	"\x04page\x18\x02 \x01(\rR\x04page\"\x80\x01\n" +
	"\x18ListSubscriptionResponse\x12C\n" +
	"\rsubscriptions\x18\x01 \x03(\v2\x1d.gmqtt.admin.api.SubscriptionR\rsubscriptions\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\rR\n" +
	"totalCount\"\xcc\x01\n" +
	"\x19FilterSubscriptionRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x1f\n" +
	"\vfilter_type\x18\x02 \x01(\tR\n" +
	"filterType\x12<\n" +
	"\n" +
	"match_type\x18\x03 \x01(\x0e2\x1d.gmqtt.admin.api.SubMatchTypeR\tmatchType\x12\x1d\n" +
	"\n" +
	"topic_name\x18\x04 \x01(\tR\ttopicName\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limit\"a\n" +
	"\x1aFilterSubscriptionResponse\x12C\n" +
	"\rsubscriptions\x18\x01 \x03(\v2\x1d.gmqtt.admin.api.SubscriptionR\rsubscriptions\"t\n" +
	"\x10SubscribeRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12C\n" +
	"\rsubscriptions\x18\x02 \x03(\v2\x1d.gmqtt.admin.api.SubscriptionR\rsubscriptions\"%\n" +
	"\x11SubscribeResponse\x12\x10\n" +
	"\x03new\x18\x01 \x03(\bR\x03new\"I\n" +
	"\x12UnsubscribeRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x16\n" +
	"\x06topics\x18\x02 \x03(\tR\x06topics\"\xe0\x01\n" +
	"\fSubscription\x12\x1d\n" +
	"\n" +
	"topic_name\x18\x01 \x01(\tR\ttopicName\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\rR\x02id\x12\x10\n" +
	"\x03qos\x18\x03 \x01(\rR\x03qos\x12\x19\n" +
	"\bno_local\x18\x04 \x01(\bR\anoLocal\x12.\n" +
	"\x13retain_as_published\x18\x05 \x01(\bR\x11retainAsPublished\x12'\n" +
	"\x0fretain_handling\x18\x06 \x01(\rR\x0eretainHandling\x12\x1b\n" +
	"\tclient_id\x18\a \x01(\tR\bclientId*\x89\x01\n" +
	"\rSubFilterType\x12#\n" +
	"\x1fSUB_FILTER_TYPE_SYS_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13SUB_FILTER_TYPE_SYS\x10\x01\x12\x1a\n" +
	"\x16SUB_FILTER_TYPE_SHARED\x10\x02\x12\x1e\n" +
	"\x1aSUB_FILTER_TYPE_NON_SHARED\x10\x03*t\n" +
	"\fSubMatchType\x12$\n" +
	" SUB_MATCH_TYPE_MATCH_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19SUB_MATCH_TYPE_MATCH_NAME\x10\x01\x12\x1f\n" +
	"\x1bSUB_MATCH_TYPE_MATCH_FILTER\x10\x022\xe9\x03\n" +
	"\x13SubscriptionService\x12v\n" +
	"\x04List\x12(.gmqtt.admin.api.ListSubscriptionRequest\x1a).gmqtt.admin.api.ListSubscriptionResponse\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/v1/subscriptions\x12\x83\x01\n" +
	"\x06Filter\x12*.gmqtt.admin.api.FilterSubscriptionRequest\x1a+.gmqtt.admin.api.FilterSubscriptionResponse\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/v1/filter_subscriptions\x12l\n" +
	"\tSubscribe\x12!.gmqtt.admin.api.SubscribeRequest\x1a\".gmqtt.admin.api.SubscribeResponse\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/v1/subscribe\x12f\n" +
	"\vUnsubscribe\x12#.gmqtt.admin.api.UnsubscribeRequest\x1a\x16.google.protobuf.Empty\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/v1/unsubscribeB\xa7\x01\n" +
	"\x13com.gmqtt.admin.apiB\x11SubscriptionProtoP\x01Z\x1fgithub.com/DrmagicE/gmqtt/admin\xa2\x02\x03GAA\xaa\x02\x0fGmqtt.Admin.Api\xca\x02\x0fGmqtt\\Admin\\Api\xe2\x02\x1bGmqtt\\Admin\\Api\\GPBMetadata\xea\x02\x11Gmqtt::Admin::Apib\x06proto3"

var (
	file_subscription_proto_rawDescOnce sync.Once
	file_subscription_proto_rawDescData []byte
)

func file_subscription_proto_rawDescGZIP() []byte {
	file_subscription_proto_rawDescOnce.Do(func() {
		file_subscription_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_subscription_proto_rawDesc), len(file_subscription_proto_rawDesc)))
	})
	return file_subscription_proto_rawDescData
}

var file_subscription_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_subscription_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_subscription_proto_goTypes = []any{
	(SubFilterType)(0),                 // 0: gmqtt.admin.api.SubFilterType
	(SubMatchType)(0),                  // 1: gmqtt.admin.api.SubMatchType
	(*ListSubscriptionRequest)(nil),    // 2: gmqtt.admin.api.ListSubscriptionRequest
	(*ListSubscriptionResponse)(nil),   // 3: gmqtt.admin.api.ListSubscriptionResponse
	(*FilterSubscriptionRequest)(nil),  // 4: gmqtt.admin.api.FilterSubscriptionRequest
	(*FilterSubscriptionResponse)(nil), // 5: gmqtt.admin.api.FilterSubscriptionResponse
	(*SubscribeRequest)(nil),           // 6: gmqtt.admin.api.SubscribeRequest
	(*SubscribeResponse)(nil),          // 7: gmqtt.admin.api.SubscribeResponse
	(*UnsubscribeRequest)(nil),         // 8: gmqtt.admin.api.UnsubscribeRequest
	(*Subscription)(nil),               // 9: gmqtt.admin.api.Subscription
	(*emptypb.Empty)(nil),              // 10: google.protobuf.Empty
}
var file_subscription_proto_depIdxs = []int32{
	9,  // 0: gmqtt.admin.api.ListSubscriptionResponse.subscriptions:type_name -> gmqtt.admin.api.Subscription
	1,  // 1: gmqtt.admin.api.FilterSubscriptionRequest.match_type:type_name -> gmqtt.admin.api.SubMatchType
	9,  // 2: gmqtt.admin.api.FilterSubscriptionResponse.subscriptions:type_name -> gmqtt.admin.api.Subscription
	9,  // 3: gmqtt.admin.api.SubscribeRequest.subscriptions:type_name -> gmqtt.admin.api.Subscription
	2,  // 4: gmqtt.admin.api.SubscriptionService.List:input_type -> gmqtt.admin.api.ListSubscriptionRequest
	4,  // 5: gmqtt.admin.api.SubscriptionService.Filter:input_type -> gmqtt.admin.api.FilterSubscriptionRequest
	6,  // 6: gmqtt.admin.api.SubscriptionService.Subscribe:input_type -> gmqtt.admin.api.SubscribeRequest
	8,  // 7: gmqtt.admin.api.SubscriptionService.Unsubscribe:input_type -> gmqtt.admin.api.UnsubscribeRequest
	3,  // 8: gmqtt.admin.api.SubscriptionService.List:output_type -> gmqtt.admin.api.ListSubscriptionResponse
	5,  // 9: gmqtt.admin.api.SubscriptionService.Filter:output_type -> gmqtt.admin.api.FilterSubscriptionResponse
	7,  // 10: gmqtt.admin.api.SubscriptionService.Subscribe:output_type -> gmqtt.admin.api.SubscribeResponse
	10, // 11: gmqtt.admin.api.SubscriptionService.Unsubscribe:output_type -> google.protobuf.Empty
	8,  // [8:12] is the sub-list for method output_type
	4,  // [4:8] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_subscription_proto_init() }
func file_subscription_proto_init() {
	if File_subscription_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_subscription_proto_rawDesc), len(file_subscription_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_subscription_proto_goTypes,
		DependencyIndexes: file_subscription_proto_depIdxs,
		EnumInfos:         file_subscription_proto_enumTypes,
		MessageInfos:      file_subscription_proto_msgTypes,
	}.Build()
	File_subscription_proto = out.File
	file_subscription_proto_goTypes = nil
	file_subscription_proto_depIdxs = nil
}
