// Code generated by MockGen. DO NOT EDIT.
// Source: server/plugin.go
//
// Generated by this command:
//
//	mockgen -source=server/plugin.go -destination=./server/plugin_mock.go -package=server
//

// Package server is a generated GoMock package.
package server

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPlugin is a mock of Plugin interface.
type MockPlugin struct {
	ctrl     *gomock.Controller
	recorder *MockPluginMockRecorder
	isgomock struct{}
}

// MockPluginMockRecorder is the mock recorder for MockPlugin.
type MockPluginMockRecorder struct {
	mock *MockPlugin
}

// NewMockPlugin creates a new mock instance.
func NewMockPlugin(ctrl *gomock.Controller) *MockPlugin {
	mock := &MockPlugin{ctrl: ctrl}
	mock.recorder = &MockPluginMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPlugin) EXPECT() *MockPluginMockRecorder {
	return m.recorder
}

// HookWrapper mocks base method.
func (m *MockPlugin) HookWrapper() HookWrapper {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HookWrapper")
	ret0, _ := ret[0].(HookWrapper)
	return ret0
}

// HookWrapper indicates an expected call of HookWrapper.
func (mr *MockPluginMockRecorder) HookWrapper() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HookWrapper", reflect.TypeOf((*MockPlugin)(nil).HookWrapper))
}

// Load mocks base method.
func (m *MockPlugin) Load(service Server) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Load", service)
	ret0, _ := ret[0].(error)
	return ret0
}

// Load indicates an expected call of Load.
func (mr *MockPluginMockRecorder) Load(service any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Load", reflect.TypeOf((*MockPlugin)(nil).Load), service)
}

// Name mocks base method.
func (m *MockPlugin) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockPluginMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockPlugin)(nil).Name))
}

// Unload mocks base method.
func (m *MockPlugin) Unload() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unload")
	ret0, _ := ret[0].(error)
	return ret0
}

// Unload indicates an expected call of Unload.
func (mr *MockPluginMockRecorder) Unload() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unload", reflect.TypeOf((*MockPlugin)(nil).Unload))
}
