// Code generated by MockGen. DO NOT EDIT.
// Source: config/config.go
//
// Generated by this command:
//
//	mockgen -source=config/config.go -destination=./config/config_mock.go -package=config
//

// Package config is a generated GoMock package.
package config

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockConfiguration is a mock of Configuration interface.
type MockConfiguration struct {
	ctrl     *gomock.Controller
	recorder *MockConfigurationMockRecorder
	isgomock struct{}
}

// MockConfigurationMockRecorder is the mock recorder for MockConfiguration.
type MockConfigurationMockRecorder struct {
	mock *MockConfiguration
}

// NewMockConfiguration creates a new mock instance.
func NewMockConfiguration(ctrl *gomock.Controller) *MockConfiguration {
	mock := &MockConfiguration{ctrl: ctrl}
	mock.recorder = &MockConfigurationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConfiguration) EXPECT() *MockConfigurationMockRecorder {
	return m.recorder
}

// UnmarshalYAML mocks base method.
func (m *MockConfiguration) UnmarshalYAML(unmarshal func(any) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnmarshalYAML", unmarshal)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnmarshalYAML indicates an expected call of UnmarshalYAML.
func (mr *MockConfigurationMockRecorder) UnmarshalYAML(unmarshal any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnmarshalYAML", reflect.TypeOf((*MockConfiguration)(nil).UnmarshalYAML), unmarshal)
}

// Validate mocks base method.
func (m *MockConfiguration) Validate() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Validate")
	ret0, _ := ret[0].(error)
	return ret0
}

// Validate indicates an expected call of Validate.
func (mr *MockConfigurationMockRecorder) Validate() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Validate", reflect.TypeOf((*MockConfiguration)(nil).Validate))
}
