// Code generated by MockGen. DO NOT EDIT.
// Source: plugin/federation/federation_grpc.pb.go
//
// Generated by this command:
//
//	mockgen -source=plugin/federation/federation_grpc.pb.go -destination=./plugin/federation/federation_grpc.pb_mock.go -package=federation
//

// Package federation is a generated GoMock package.
package federation

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// MockMembershipClient is a mock of MembershipClient interface.
type MockMembershipClient struct {
	ctrl     *gomock.Controller
	recorder *MockMembershipClientMockRecorder
	isgomock struct{}
}

// MockMembershipClientMockRecorder is the mock recorder for MockMembershipClient.
type MockMembershipClientMockRecorder struct {
	mock *MockMembershipClient
}

// NewMockMembershipClient creates a new mock instance.
func NewMockMembershipClient(ctrl *gomock.Controller) *MockMembershipClient {
	mock := &MockMembershipClient{ctrl: ctrl}
	mock.recorder = &MockMembershipClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMembershipClient) EXPECT() *MockMembershipClientMockRecorder {
	return m.recorder
}

// ForceLeave mocks base method.
func (m *MockMembershipClient) ForceLeave(ctx context.Context, in *ForceLeaveRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ForceLeave", varargs...)
	ret0, _ := ret[0].(*emptypb.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ForceLeave indicates an expected call of ForceLeave.
func (mr *MockMembershipClientMockRecorder) ForceLeave(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ForceLeave", reflect.TypeOf((*MockMembershipClient)(nil).ForceLeave), varargs...)
}

// Join mocks base method.
func (m *MockMembershipClient) Join(ctx context.Context, in *JoinRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Join", varargs...)
	ret0, _ := ret[0].(*emptypb.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Join indicates an expected call of Join.
func (mr *MockMembershipClientMockRecorder) Join(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Join", reflect.TypeOf((*MockMembershipClient)(nil).Join), varargs...)
}

// Leave mocks base method.
func (m *MockMembershipClient) Leave(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Leave", varargs...)
	ret0, _ := ret[0].(*emptypb.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Leave indicates an expected call of Leave.
func (mr *MockMembershipClientMockRecorder) Leave(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Leave", reflect.TypeOf((*MockMembershipClient)(nil).Leave), varargs...)
}

// ListMembers mocks base method.
func (m *MockMembershipClient) ListMembers(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListMembersResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListMembers", varargs...)
	ret0, _ := ret[0].(*ListMembersResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMembers indicates an expected call of ListMembers.
func (mr *MockMembershipClientMockRecorder) ListMembers(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMembers", reflect.TypeOf((*MockMembershipClient)(nil).ListMembers), varargs...)
}

// MockMembershipServer is a mock of MembershipServer interface.
type MockMembershipServer struct {
	ctrl     *gomock.Controller
	recorder *MockMembershipServerMockRecorder
	isgomock struct{}
}

// MockMembershipServerMockRecorder is the mock recorder for MockMembershipServer.
type MockMembershipServerMockRecorder struct {
	mock *MockMembershipServer
}

// NewMockMembershipServer creates a new mock instance.
func NewMockMembershipServer(ctrl *gomock.Controller) *MockMembershipServer {
	mock := &MockMembershipServer{ctrl: ctrl}
	mock.recorder = &MockMembershipServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMembershipServer) EXPECT() *MockMembershipServerMockRecorder {
	return m.recorder
}

// ForceLeave mocks base method.
func (m *MockMembershipServer) ForceLeave(arg0 context.Context, arg1 *ForceLeaveRequest) (*emptypb.Empty, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ForceLeave", arg0, arg1)
	ret0, _ := ret[0].(*emptypb.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ForceLeave indicates an expected call of ForceLeave.
func (mr *MockMembershipServerMockRecorder) ForceLeave(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ForceLeave", reflect.TypeOf((*MockMembershipServer)(nil).ForceLeave), arg0, arg1)
}

// Join mocks base method.
func (m *MockMembershipServer) Join(arg0 context.Context, arg1 *JoinRequest) (*emptypb.Empty, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Join", arg0, arg1)
	ret0, _ := ret[0].(*emptypb.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Join indicates an expected call of Join.
func (mr *MockMembershipServerMockRecorder) Join(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Join", reflect.TypeOf((*MockMembershipServer)(nil).Join), arg0, arg1)
}

// Leave mocks base method.
func (m *MockMembershipServer) Leave(arg0 context.Context, arg1 *emptypb.Empty) (*emptypb.Empty, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Leave", arg0, arg1)
	ret0, _ := ret[0].(*emptypb.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Leave indicates an expected call of Leave.
func (mr *MockMembershipServerMockRecorder) Leave(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Leave", reflect.TypeOf((*MockMembershipServer)(nil).Leave), arg0, arg1)
}

// ListMembers mocks base method.
func (m *MockMembershipServer) ListMembers(arg0 context.Context, arg1 *emptypb.Empty) (*ListMembersResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMembers", arg0, arg1)
	ret0, _ := ret[0].(*ListMembersResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMembers indicates an expected call of ListMembers.
func (mr *MockMembershipServerMockRecorder) ListMembers(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMembers", reflect.TypeOf((*MockMembershipServer)(nil).ListMembers), arg0, arg1)
}

// mustEmbedUnimplementedMembershipServer mocks base method.
func (m *MockMembershipServer) mustEmbedUnimplementedMembershipServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedMembershipServer")
}

// mustEmbedUnimplementedMembershipServer indicates an expected call of mustEmbedUnimplementedMembershipServer.
func (mr *MockMembershipServerMockRecorder) mustEmbedUnimplementedMembershipServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedMembershipServer", reflect.TypeOf((*MockMembershipServer)(nil).mustEmbedUnimplementedMembershipServer))
}

// MockUnsafeMembershipServer is a mock of UnsafeMembershipServer interface.
type MockUnsafeMembershipServer struct {
	ctrl     *gomock.Controller
	recorder *MockUnsafeMembershipServerMockRecorder
	isgomock struct{}
}

// MockUnsafeMembershipServerMockRecorder is the mock recorder for MockUnsafeMembershipServer.
type MockUnsafeMembershipServerMockRecorder struct {
	mock *MockUnsafeMembershipServer
}

// NewMockUnsafeMembershipServer creates a new mock instance.
func NewMockUnsafeMembershipServer(ctrl *gomock.Controller) *MockUnsafeMembershipServer {
	mock := &MockUnsafeMembershipServer{ctrl: ctrl}
	mock.recorder = &MockUnsafeMembershipServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUnsafeMembershipServer) EXPECT() *MockUnsafeMembershipServerMockRecorder {
	return m.recorder
}

// mustEmbedUnimplementedMembershipServer mocks base method.
func (m *MockUnsafeMembershipServer) mustEmbedUnimplementedMembershipServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedMembershipServer")
}

// mustEmbedUnimplementedMembershipServer indicates an expected call of mustEmbedUnimplementedMembershipServer.
func (mr *MockUnsafeMembershipServerMockRecorder) mustEmbedUnimplementedMembershipServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedMembershipServer", reflect.TypeOf((*MockUnsafeMembershipServer)(nil).mustEmbedUnimplementedMembershipServer))
}

// MockFederationClient is a mock of FederationClient interface.
type MockFederationClient struct {
	ctrl     *gomock.Controller
	recorder *MockFederationClientMockRecorder
	isgomock struct{}
}

// MockFederationClientMockRecorder is the mock recorder for MockFederationClient.
type MockFederationClientMockRecorder struct {
	mock *MockFederationClient
}

// NewMockFederationClient creates a new mock instance.
func NewMockFederationClient(ctrl *gomock.Controller) *MockFederationClient {
	mock := &MockFederationClient{ctrl: ctrl}
	mock.recorder = &MockFederationClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFederationClient) EXPECT() *MockFederationClientMockRecorder {
	return m.recorder
}

// EventStream mocks base method.
func (m *MockFederationClient) EventStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Event, Ack], error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "EventStream", varargs...)
	ret0, _ := ret[0].(grpc.BidiStreamingClient[Event, Ack])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EventStream indicates an expected call of EventStream.
func (mr *MockFederationClientMockRecorder) EventStream(ctx any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EventStream", reflect.TypeOf((*MockFederationClient)(nil).EventStream), varargs...)
}

// Hello mocks base method.
func (m *MockFederationClient) Hello(ctx context.Context, in *ClientHello, opts ...grpc.CallOption) (*ServerHello, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Hello", varargs...)
	ret0, _ := ret[0].(*ServerHello)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Hello indicates an expected call of Hello.
func (mr *MockFederationClientMockRecorder) Hello(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Hello", reflect.TypeOf((*MockFederationClient)(nil).Hello), varargs...)
}

// MockFederationServer is a mock of FederationServer interface.
type MockFederationServer struct {
	ctrl     *gomock.Controller
	recorder *MockFederationServerMockRecorder
	isgomock struct{}
}

// MockFederationServerMockRecorder is the mock recorder for MockFederationServer.
type MockFederationServerMockRecorder struct {
	mock *MockFederationServer
}

// NewMockFederationServer creates a new mock instance.
func NewMockFederationServer(ctrl *gomock.Controller) *MockFederationServer {
	mock := &MockFederationServer{ctrl: ctrl}
	mock.recorder = &MockFederationServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFederationServer) EXPECT() *MockFederationServerMockRecorder {
	return m.recorder
}

// EventStream mocks base method.
func (m *MockFederationServer) EventStream(arg0 grpc.BidiStreamingServer[Event, Ack]) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EventStream", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// EventStream indicates an expected call of EventStream.
func (mr *MockFederationServerMockRecorder) EventStream(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EventStream", reflect.TypeOf((*MockFederationServer)(nil).EventStream), arg0)
}

// Hello mocks base method.
func (m *MockFederationServer) Hello(arg0 context.Context, arg1 *ClientHello) (*ServerHello, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Hello", arg0, arg1)
	ret0, _ := ret[0].(*ServerHello)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Hello indicates an expected call of Hello.
func (mr *MockFederationServerMockRecorder) Hello(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Hello", reflect.TypeOf((*MockFederationServer)(nil).Hello), arg0, arg1)
}

// mustEmbedUnimplementedFederationServer mocks base method.
func (m *MockFederationServer) mustEmbedUnimplementedFederationServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedFederationServer")
}

// mustEmbedUnimplementedFederationServer indicates an expected call of mustEmbedUnimplementedFederationServer.
func (mr *MockFederationServerMockRecorder) mustEmbedUnimplementedFederationServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedFederationServer", reflect.TypeOf((*MockFederationServer)(nil).mustEmbedUnimplementedFederationServer))
}

// MockUnsafeFederationServer is a mock of UnsafeFederationServer interface.
type MockUnsafeFederationServer struct {
	ctrl     *gomock.Controller
	recorder *MockUnsafeFederationServerMockRecorder
	isgomock struct{}
}

// MockUnsafeFederationServerMockRecorder is the mock recorder for MockUnsafeFederationServer.
type MockUnsafeFederationServerMockRecorder struct {
	mock *MockUnsafeFederationServer
}

// NewMockUnsafeFederationServer creates a new mock instance.
func NewMockUnsafeFederationServer(ctrl *gomock.Controller) *MockUnsafeFederationServer {
	mock := &MockUnsafeFederationServer{ctrl: ctrl}
	mock.recorder = &MockUnsafeFederationServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUnsafeFederationServer) EXPECT() *MockUnsafeFederationServerMockRecorder {
	return m.recorder
}

// mustEmbedUnimplementedFederationServer mocks base method.
func (m *MockUnsafeFederationServer) mustEmbedUnimplementedFederationServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedFederationServer")
}

// mustEmbedUnimplementedFederationServer indicates an expected call of mustEmbedUnimplementedFederationServer.
func (mr *MockUnsafeFederationServerMockRecorder) mustEmbedUnimplementedFederationServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedFederationServer", reflect.TypeOf((*MockUnsafeFederationServer)(nil).mustEmbedUnimplementedFederationServer))
}
